title: amarjeetsaini
description: >- 
    <a href='/index'>Home</a> | <a href='/programming'>Programming</a> | <a href='/books'>Books</a> | <a href='/articles'>Articles</a> | <a href='/misc'>Misc</a> | <a href='/connect_with_me'>Connect With Me</a>

# Build settings
# markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
