title: amarjeet
description: >- 
    <a href='/index'>Home</a> | <a href='/projects'>Projects</a> | <a href='/blogs'>Blogs</a> | <a href='/cv'>CV</a> | <a href='/connect_with_me'>Connect With Me</a>

# Build settings
# markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
